# Generated by Django 5.1.4 on 2024-12-31 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("file_name", models.CharField(max_length=255)),
                ("width", models.IntegerField()),
                ("height", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Annotation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("bbox", models.JSONField()),
                ("area", models.IntegerField()),
                ("iscrowd", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="App.category"
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="App.image"
                    ),
                ),
            ],
        ),
    ]
